/* eslint-disable react-hooks/set-state-in-effect */
"use client";

import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import "./game.css";
import { advanceTownDay, buildingProduction, calculateJoy, canAfford, isValidSave, moraleMultiplier, nextVisitorDay, policyModifiers, proportionalTrade, requestWaitDays, scoreTitle, seasonalFoodIncome, townScore, upgradeSalvage, visitorForDay, withinRadius } from "./game-model";

type Resource = { wood:number; stone:number; food:number; mana:number; folk:number };
type Kind = "road"|"cottage"|"farm"|"lumber"|"quarry"|"well"|"shrine"|"market"|"tower";
type Tool = Kind|"demolish";
type Policy = "balanced"|"harvest"|"arcane";
type Building = { id:number; kind:Kind; x:number; y:number; level:number };
type ChronicleEntry = { day:number; text:string };
type Save = { resources:Resource; buildings:Building[]; day:number; renown:number; chapter:number; deeds?:number; speed?:1|2; sound?:boolean; earned?:string[]; history?:ChronicleEntry[]; policy?:Policy; continued?:boolean; nextRequestDay?:number; lastVisitorDay?:number };
type UndoState = { resources:Resource; buildings:Building[]; renown:number; message:string };

const COLS=12, ROWS=8, WELL_RADIUS=2, SHRINE_RADIUS=2.3, SAVE_KEY="glimmerglen-save-v2";
const BUILDINGS:Record<Kind,{name:string;icon:string;cost:Partial<Resource>;hint:string;unlock:number;refund:Partial<Resource>}>= {
  road:{name:"Lantern Road",icon:"—",cost:{wood:2},refund:{wood:1},hint:"Connects neighboring workshops",unlock:1},
  cottage:{name:"Moss Cottage",icon:"⌂",cost:{wood:16,stone:6},refund:{wood:8,stone:3},hint:"Homes 2 folk · uses 1 food",unlock:1},
  farm:{name:"Moonwheat Field",icon:"≋",cost:{wood:10},refund:{wood:5},hint:"4 food · doubled by magic",unlock:1},
  lumber:{name:"Forester Lodge",icon:"♧",cost:{wood:8,stone:3},refund:{wood:4,stone:1},hint:"4 wood · +2 by forest",unlock:1},
  quarry:{name:"Stonecircle",icon:"◆",cost:{wood:10},refund:{wood:5},hint:"3 stone · +2 by crags",unlock:1},
  well:{name:"Wishing Well",icon:"◉",cost:{stone:14},refund:{stone:7},hint:"Adds 2 food to close farms",unlock:1},
  shrine:{name:"Bloom Shrine",icon:"✦",cost:{wood:18,stone:12},refund:{wood:9,stone:6},hint:"2 mana · enchants nearby land",unlock:1},
  market:{name:"Lantern Market",icon:"¤",cost:{wood:24,stone:10},refund:{wood:12,stone:5},hint:"Raises joy across the town",unlock:2},
  tower:{name:"Starwatch Tower",icon:"☾",cost:{stone:28,mana:12},refund:{stone:14},hint:"5 mana · raises renown",unlock:3},
};
const START_BUILDINGS:Building[]=[{id:1,kind:"cottage",x:5,y:4,level:1},{id:2,kind:"farm",x:4,y:4,level:1},{id:3,kind:"lumber",x:3,y:2,level:1}];
const INITIAL:Resource={wood:52,stone:30,food:38,mana:0,folk:4};
const terrain:Record<string,"forest"|"crag"|"pond">={"0,0":"forest","1,0":"forest","0,1":"forest","6,0":"forest","2,6":"forest","2,7":"forest","3,7":"forest","10,0":"crag","11,0":"crag","11,1":"crag","9,6":"crag","10,6":"crag","10,7":"crag","11,7":"crag","1,5":"pond"};
const seasons=[{name:"Dewspring",food:1.2,wood:1},{name:"Suncrest",food:1.35,wood:.9},{name:"Amberfall",food:1,wood:1.3},{name:"Frostwane",food:.7,wood:1}];
const requests=[
  {title:"Pilgrims at the south road",copy:"Send provisions for their onward journey.",cost:{food:24},reward:"+4 renown · +8 mana"},
  {title:"The bridgewright’s levy",copy:"Timber will reopen the old crossing.",cost:{wood:30,stone:8},reward:"+6 renown · +18 food"},
  {title:"Star charts for the academy",copy:"Lend mana to the hilltop astronomers.",cost:{mana:22},reward:"+8 renown · +20 stone"},
] as const;
const chapters=[
  {name:"Wake the sleeping vale",copy:"Build a home where magic and mortal craft flourish together.",goals:[["Welcome 10 folk","folk",10],["Store 60 food","food",60],["Gather 20 mana","mana",20]] as const},
  {name:"Light the woodland roads",copy:"A true town needs fellowship, trade, and warm lanterns after dusk.",goals:[["Welcome 16 folk","folk",16],["Earn 12 renown","renown",12],["Raise a Lantern Market","market",1]] as const},
  {name:"Read the crown of stars",copy:"Build a landmark worthy of the old stories and make the valley sing.",goals:[["Raise a Starwatch Tower","tower",1],["Gather 50 mana","mana",50],["Reach 85 joy","joy",85]] as const},
];

const key=(x:number,y:number)=>`${x},${y}`;
const canPay=(r:Resource,c:Partial<Resource>)=>canAfford(r,c as Record<string,number>);
const moveTileFocus=(e:React.KeyboardEvent<HTMLButtonElement>,x:number,y:number)=>{const delta:Record<string,[number,number]>={ArrowLeft:[-1,0],ArrowRight:[1,0],ArrowUp:[0,-1],ArrowDown:[0,1]};if(!delta[e.key])return;e.preventDefault();const [dx,dy]=delta[e.key],nx=Math.max(0,Math.min(COLS-1,x+dx)),ny=Math.max(0,Math.min(ROWS-1,y+dy));document.querySelector<HTMLButtonElement>(`[data-tile="${nx},${ny}"]`)?.focus()};
const trapModalFocus=(e:KeyboardEvent)=>{const modal=document.querySelector(".choice-layer,.victory");if(!modal)return;const controls=[...modal.querySelectorAll<HTMLElement>("button:not(:disabled),input:not([tabindex='-1']):not(:disabled),[tabindex='0']")],current=controls.indexOf(document.activeElement as HTMLElement);if(!controls.length)return;e.preventDefault();const next=current<0?(e.shiftKey?controls.length-1:0):(current+(e.shiftKey?-1:1)+controls.length)%controls.length;controls[next].focus()};

export default function Home(){
  const [resources,setResources]=useState(INITIAL),[buildings,setBuildings]=useState<Building[]>(START_BUILDINGS);
  const [tool,setTool]=useState<Tool>("farm"),[day,setDay]=useState(1),[paused,setPaused]=useState(false);
  const [message,setMessage]=useState("The glen is waiting. Choose a craft from the folio."),[event,setEvent]=useState("A soft rain has blessed the valley.");
  const [renown,setRenown]=useState(0),[chapter,setChapter]=useState(0),[deeds,setDeeds]=useState(0),[inspect,setInspect]=useState<number|null>(null),[saved,setSaved]=useState(false),[ready,setReady]=useState(false);
  const [earned,setEarned]=useState<string[]>([]),[lastMark,setLastMark]=useState<string|null>(null);
  const [history,setHistory]=useState<ChronicleEntry[]>([{day:1,text:"A soft rain has blessed the valley."}]);
  const [choice,setChoice]=useState<null|"merchant"|"spirit"|"druid"|"storm">(null),[showGuide,setShowGuide]=useState(true),[speed,setSpeed]=useState<1|2>(1),[hoverTile,setHoverTile]=useState<{x:number;y:number}|null>(null),nextId=useRef(4);
  const focusReturn=useRef<HTMLElement|null>(null);
  const [sound,setSound]=useState(true),[showLedger,setShowLedger]=useState(false),[undo,setUndo]=useState<UndoState|null>(null);
  const [pageVisible,setPageVisible]=useState(true);
  const [confirmRestart,setConfirmRestart]=useState(false);
  const [won,setWon]=useState(false);
  const [sandbox,setSandbox]=useState(false);
  const [policy,setPolicy]=useState<Policy>("balanced");
  const [nextRequestDay,setNextRequestDay]=useState(1);
  const [lastVisitorDay,setLastVisitorDay]=useState(0);
  const [activeTile,setActiveTile]=useState(0);
  const starving=useRef(false);
  const townCanvas=useRef<HTMLCanvasElement|null>(null);
  const chime=useCallback((tone:"place"|"magic"|"success"|"error"="place")=>{if(!sound)return;try{const AudioCtx=window.AudioContext||(window as typeof window&{webkitAudioContext:typeof AudioContext}).webkitAudioContext;const ctx=new AudioCtx(),osc=ctx.createOscillator(),gain=ctx.createGain();osc.type=tone==="error"?"sawtooth":"sine";osc.frequency.value={place:392,magic:659,success:523,error:180}[tone];gain.gain.setValueAtTime(.05,ctx.currentTime);gain.gain.exponentialRampToValueAtTime(.001,ctx.currentTime+.25);osc.connect(gain);gain.connect(ctx.destination);osc.start();osc.stop(ctx.currentTime+.26);osc.addEventListener("ended",()=>ctx.close())}catch{/* Audio is optional; unsupported browsers remain silent. */}},[sound]);

  useEffect(()=>{try{const raw=localStorage.getItem(SAVE_KEY);if(raw){const parsed:unknown=JSON.parse(raw);if(isValidSave(parsed)){const s=parsed as Save,loadedHistory=s.history?.slice(-8)??[{day:s.day,text:"The glen remembered your care."}];setResources(s.resources);setBuildings(s.buildings);setDay(s.day);setRenown(s.renown);setChapter(s.chapter);setDeeds(s.deeds??0);setNextRequestDay(s.nextRequestDay??s.day);setLastVisitorDay(s.lastVisitorDay??0);setSpeed(s.speed??1);setSound(s.sound??true);setPolicy(s.policy??"balanced");setSandbox(s.continued??false);setEarned(s.earned??[]);setHistory(loadedHistory);setEvent(loadedHistory.at(-1)?.text??"A soft rain has blessed the valley.");nextId.current=Math.max(...s.buildings.map(b=>b.id),0)+1;setMessage("Welcome back. The glen remembered your care.");setShowGuide(false)}else{localStorage.removeItem(SAVE_KEY);setMessage("A damaged chronicle was set aside. A fresh glen awaits.")}}}catch{localStorage.removeItem(SAVE_KEY);setMessage("A damaged chronicle was set aside. A fresh glen awaits.")}setReady(true)},[]);
  useEffect(()=>{const onVisibility=()=>setPageVisible(!document.hidden);onVisibility();document.addEventListener("visibilitychange",onVisibility);return()=>document.removeEventListener("visibilitychange",onVisibility)},[]);
  useEffect(()=>{if(!ready)return;const t=setTimeout(()=>{try{localStorage.setItem(SAVE_KEY,JSON.stringify({resources,buildings,day,renown,chapter,deeds,nextRequestDay,lastVisitorDay,speed,sound,earned,history,policy,continued:sandbox}));setSaved(true);setTimeout(()=>setSaved(false),900)}catch{setMessage("The chronicle could not be saved. A downloaded copy is recommended.")}},600);return()=>clearTimeout(t)},[resources,buildings,day,renown,chapter,deeds,nextRequestDay,lastVisitorDay,speed,sound,earned,history,policy,sandbox,ready]);
  useEffect(()=>{if(!ready)return;const flush=()=>{try{localStorage.setItem(SAVE_KEY,JSON.stringify({resources,buildings,day,renown,chapter,deeds,nextRequestDay,lastVisitorDay,speed,sound,earned,history,policy,continued:sandbox}))}catch{/* The visible autosave warning handles storage failures. */}};window.addEventListener("pagehide",flush);return()=>window.removeEventListener("pagehide",flush)},[resources,buildings,day,renown,chapter,deeds,nextRequestDay,lastVisitorDay,speed,sound,earned,history,policy,sandbox,ready]);
  useEffect(()=>{if(!ready)return;setHistory(h=>h.at(-1)?.text===event?h:[...h,{day,text:event}].slice(-8))},[event,day,ready]);
  useEffect(()=>{if(resources.food===0&&!starving.current){starving.current=true;setEvent("The granaries stand empty. Folk will leave each day until food returns.");setMessage("Food stores are empty—restore a positive harvest quickly.");chime("error")}else if(resources.food>0&&starving.current){starving.current=false;setEvent("Warm bread returns to every hearth. The lean days are ending.")}},[resources.food,chime]);

  const season=seasons[Math.floor((day-1)/8)%4];
  useEffect(()=>{
    const canvas=townCanvas.current,ctx=canvas?.getContext("2d");if(!canvas||!ctx)return;
    let raf=0,w=0,h=0,dead=false;const atlas=new Image();atlas.src="/assets/glimmerglen-building-atlas.webp";
    const fit=()=>{const r=canvas.getBoundingClientRect(),d=Math.min(devicePixelRatio||1,2);w=r.width;h=r.height;canvas.width=w*d;canvas.height=h*d;ctx.setTransform(d,0,0,d,0,0)};const ro=new ResizeObserver(fit);ro.observe(canvas);fit();
    const sprites:Record<Kind,number>={road:0,cottage:1,farm:2,lumber:3,quarry:4,well:5,shrine:6,market:7,tower:8};
    const tree=(x:number,y:number,s:number,t:number)=>{ctx.save();ctx.translate(x,y);ctx.rotate(Math.sin(t)*.018);ctx.fillStyle="#503f27";ctx.fillRect(-s*.09,s*.25,s*.18,s*.72);ctx.fillStyle="#163a27";for(let q=0;q<4;q++){ctx.beginPath();ctx.ellipse(0,-s*.54+q*s*.37,s*(.34+q*.1),s*.34,-.05,0,Math.PI*2);ctx.fill()}ctx.fillStyle="#3c7041";for(let q=0;q<3;q++){ctx.beginPath();ctx.ellipse(-s*.14,-s*.58+q*s*.4,s*(.18+q*.07),s*.18,-.35,0,Math.PI*2);ctx.fill()}ctx.fillStyle="#77915a77";ctx.beginPath();ctx.arc(-s*.12,-s*.65,s*.1,0,Math.PI*2);ctx.fill();ctx.restore()};
    const paint=(ms:number)=>{if(dead)return;const t=ms/1000,cw=w/COLS,ch=h/ROWS,seasonColors=season.name==="Frostwane"?["#527368","#3f6258"]:season.name==="Amberfall"?["#768057","#596e4c"]:["#71925e","#4d754e"],g=ctx.createLinearGradient(0,0,w,h);g.addColorStop(0,seasonColors[0]);g.addColorStop(1,seasonColors[1]);ctx.fillStyle=g;ctx.fillRect(0,0,w,h);
      for(let y=0;y<ROWS;y++)for(let x=0;x<COLS;x++){const px=x*cw,py=y*ch,land=terrain[key(x,y)],seed=x*31+y*47;ctx.fillStyle=(x+y)%3?"#fff5":"#17351d24";for(let n=0;n<4;n++)ctx.fillRect(px+((seed+n*23)%89)/100*cw,py+((seed+n*41)%83)/100*ch,1,3);if(land==="forest"){tree(px+cw*.38,py+ch*.57,ch*.32,t+x);tree(px+cw*.68,py+ch*.68,ch*.24,t*.8+y)}if(land==="crag"){ctx.fillStyle="#627168";ctx.beginPath();ctx.moveTo(px+cw*.5,py+ch*.12);ctx.lineTo(px+cw*.82,py+ch*.9);ctx.lineTo(px+cw*.16,py+ch*.88);ctx.closePath();ctx.fill();ctx.fillStyle="#9aa18b";ctx.beginPath();ctx.moveTo(px+cw*.5,py+ch*.12);ctx.lineTo(px+cw*.53,py+ch*.76);ctx.lineTo(px+cw*.25,py+ch*.7);ctx.closePath();ctx.fill()}if(land==="pond"){ctx.fillStyle="#65a29b";ctx.beginPath();ctx.ellipse(px+cw*.5,py+ch*.55,cw*.42,ch*.28,0,0,Math.PI*2);ctx.fill();ctx.strokeStyle="#d8f1dd99";ctx.beginPath();ctx.ellipse(px+cw*.5,py+ch*.54,cw*(.16+Math.sin(t*2)*.015),ch*.07,0,0,Math.PI*2);ctx.stroke()}}
      const routeHomes=buildings.filter(b=>b.kind==="cottage"),routeJobs=buildings.filter(b=>!["cottage","road","well"].includes(b.kind));ctx.lineCap="round";routeJobs.forEach((b,i)=>{const a=routeHomes[i%Math.max(1,routeHomes.length)];if(!a)return;ctx.strokeStyle="#d7bd7b25";ctx.lineWidth=Math.max(3,cw*.08);ctx.beginPath();ctx.moveTo((a.x+.5)*cw,(a.y+.7)*ch);ctx.bezierCurveTo((a.x+.5)*cw,(b.y+.5)*ch,(b.x+.5)*cw,(a.y+.5)*ch,(b.x+.5)*cw,(b.y+.7)*ch);ctx.stroke();ctx.strokeStyle="#5b633d22";ctx.lineWidth=1;ctx.setLineDash([3,7]);ctx.stroke();ctx.setLineDash([])});
      if(atlas.complete)buildings.slice().sort((a,b)=>a.y-b.y).forEach(b=>{const n=sprites[b.kind],sx=n%3*atlas.width/3,sy=Math.floor(n/3)*atlas.height/3,cx=(b.x+.5)*cw,cy=(b.y+.55)*ch,dw=cw*(b.kind==="road"?1.15:1.5),dh=ch*(b.kind==="road"?1.15:1.5);ctx.save();if(b.kind==="shrine"){ctx.shadowColor="#caff8f";ctx.shadowBlur=18+Math.sin(t*2)*6}ctx.drawImage(atlas,sx,sy,atlas.width/3,atlas.height/3,cx-dw/2,cy-dh*.65,dw,dh);ctx.restore();if(b.kind==="cottage")for(let q=0;q<3;q++){const a=(t*.16+q*.3)%1;ctx.fillStyle=`rgba(235,225,190,${(1-a)*.3})`;ctx.beginPath();ctx.arc(cx+4+a*9,cy-dh*.52-a*20,2+a*3,0,Math.PI*2);ctx.fill()}if(b.kind==="farm"){ctx.strokeStyle="#f6da78aa";for(let q=-2;q<3;q++){ctx.beginPath();ctx.moveTo(cx+q*4,cy+ch*.13);ctx.quadraticCurveTo(cx+q*4+Math.sin(t*2+q)*3,cy-ch*.02,cx+q*4+Math.sin(t*2+q)*2,cy-ch*.18);ctx.stroke()}}if(b.kind==="well"){ctx.strokeStyle="#cdf0df99";ctx.beginPath();ctx.ellipse(cx,cy-ch*.05,8+Math.sin(t*2),3,0,0,Math.PI*2);ctx.stroke()}if(b.kind==="market"||b.kind==="tower"){ctx.fillStyle=`rgba(255,218,112,${.45+.3*Math.sin(t*3)**2})`;ctx.beginPath();ctx.arc(cx+dw*.18,cy-dh*.28,2.3,0,Math.PI*2);ctx.fill()}});
      const homes=buildings.filter(b=>b.kind==="cottage"),jobs=buildings.filter(b=>!["cottage","road","well"].includes(b.kind));if(homes.length&&jobs.length)Array.from({length:Math.min(resources.folk,10)},(_,i)=>{const a=homes[i%homes.length],b=jobs[i%jobs.length],c=(t*.06+i*.16)%1,p=c<.42?c/.42:c<.62?1:c<.95?1-(c-.62)/.33:0,e=p*p*(3-2*p),x=(a.x+(b.x-a.x)*e+.5)*cw,y=(a.y+(b.y-a.y)*e+.65)*ch,step=Math.sin(t*12+i)*1.3;ctx.fillStyle="#e6b77c";ctx.beginPath();ctx.arc(x,y-8+step,3.2,0,Math.PI*2);ctx.fill();ctx.fillStyle=["#984d3d","#47758d","#69558a","#477652"][i%4];ctx.fillRect(x-4,y-4+step,8,10);ctx.fillStyle="#292824";ctx.fillRect(x-4,y+6+step,3,4);ctx.fillRect(x+1,y+6-step,3,4)});for(let i=0;i<10;i++){ctx.fillStyle=`rgba(244,231,132,${.18+.2*Math.sin(t*2+i)**2})`;ctx.beginPath();ctx.arc((i*91+t*5)%w,(i*53+Math.sin(t+i)*12)%h,1.2,0,Math.PI*2);ctx.fill()}raf=requestAnimationFrame(paint)};raf=requestAnimationFrame(paint);return()=>{dead=true;cancelAnimationFrame(raf);ro.disconnect()}
  },[buildings,resources.folk,season.name]);
  const nextVisitor=nextVisitorDay(day);
  const rememberTown=()=>setUndo({resources:{...resources},buildings:buildings.map(b=>({...b})),renown,message});
  const undoLast=()=>{if(!undo)return;setResources(undo.resources);setBuildings(undo.buildings);setRenown(undo.renown);setMessage(`Undone: ${undo.message}`);setInspect(null);nextId.current=Math.max(...undo.buildings.map(b=>b.id),0)+1;setUndo(null);chime("place")};
  const isMagic=useCallback((x:number,y:number)=>buildings.some(b=>b.kind==="shrine"&&withinRadius({x,y},b,SHRINE_RADIUS)),[buildings]);
  const counts=useMemo(()=>Object.fromEntries(Object.keys(BUILDINGS).map(k=>[k,buildings.filter(b=>b.kind===k).length])) as Record<Kind,number>,[buildings]);
  const ranks=useMemo(()=>Object.fromEntries(Object.keys(BUILDINGS).map(k=>[k,buildings.filter(b=>b.kind===k).reduce((sum,b)=>sum+b.level,0)])) as Record<Kind,number>,[buildings]);
  const policyBoost=useMemo(()=>policyModifiers(policy),[policy]);
  const joy=useMemo(()=>Math.min(100,calculateJoy({shrines:ranks.shrine,markets:ranks.market,wells:ranks.well,roads:counts.road,food:resources.food,folk:resources.folk,cottages:ranks.cottage})+policyBoost.joy),[counts.road,ranks,resources,policyBoost.joy]);
  const morale=moraleMultiplier(joy);
  const income=useMemo(()=>{let wood=1,stone=0,foodProduction=0,foodUpkeep=0,mana=0,glory=0;buildings.forEach(b=>{const linked=buildings.some(r=>r.kind==="road"&&Math.abs(r.x-b.x)+Math.abs(r.y-b.y)===1),wellRank=Math.max(0,...buildings.filter(w=>w.kind==="well"&&withinRadius(b,w,WELL_RADIUS)).map(w=>w.level)),made=buildingProduction({kind:b.kind,level:b.level,linked,morale,terrainBonus:(b.kind==="lumber"&&b.x<4)||(b.kind==="quarry"&&b.x>8),enchanted:isMagic(b.x,b.y),wellRank});wood+=made.wood;stone+=made.stone;if(made.food>=0)foodProduction+=made.food;else foodUpkeep+=made.food;mana+=made.mana;glory+=made.glory});return{wood:Math.floor(wood*season.wood*policyBoost.craft),stone:Math.floor(stone*policyBoost.craft),food:seasonalFoodIncome(foodProduction,foodUpkeep,season.food,policyBoost.food),mana:Math.floor(mana*policyBoost.mana),glory}},[buildings,isMagic,season,morale,policyBoost]);

  useEffect(()=>{if(paused||choice||showGuide||showLedger||confirmRestart||undo||(won&&!sandbox)||!pageVisible)return;const t=setInterval(()=>{setDay(d=>d+1);setResources(r=>advanceTownDay(r,income));if(income.glory)setRenown(v=>v+income.glory)},2400/speed);return()=>clearInterval(t)},[paused,choice,showGuide,showLedger,confirmRestart,undo,won,sandbox,pageVisible,income,speed]);
  useEffect(()=>{if(!undo)return;const t=setTimeout(()=>setUndo(null),7000);return()=>clearTimeout(t)},[undo]);
  useEffect(()=>{const visitor=visitorForDay(day);if(visitor&&lastVisitorDay!==day)setChoice(visitor);if(day%8===1&&day>1)setEvent(`${season.name} settles over the valley. The harvest rhythm has changed.`)},[day,season.name,lastVisitorDay]);

  const value=(metric:string)=>metric==="renown"?renown:metric==="joy"?joy:metric in counts?counts[metric as Kind]:resources[metric as keyof Resource];
  const chapterDone=chapters[chapter].goals.every(g=>value(g[1])>=g[2]);
  useEffect(()=>{if(!chapterDone)return;setUndo(null);if(chapter<2){setChapter(c=>c+1);setRenown(r=>r+5);setEvent("A new chapter opens in the town chronicle.");setMessage("The valley has taken notice. New craft is now unlocked.");chime("success")}else setWon(true)},[chapterDone,chapter,chime]);

  const act=(x:number,y:number)=>{
    const existing=buildings.find(b=>b.x===x&&b.y===y),land=terrain[key(x,y)];
    if(existing){if(tool==="demolish"){rememberTown();const refund=BUILDINGS[existing.kind].refund,salvage=upgradeSalvage(existing.level);setBuildings(bs=>bs.filter(b=>b.id!==existing.id));setResources(r=>{const n={...r};Object.entries(refund).forEach(([k,v])=>n[k as keyof Resource]+=v!);n.wood+=salvage.wood;n.stone+=salvage.stone;if(existing.kind==="cottage")n.folk=Math.max(2,n.folk-existing.level*2);return n});setMessage(`${BUILDINGS[existing.kind].name} cleared. Half its materials were recovered.`);setInspect(null);chime("place")}else setInspect(existing.id);return}
    if(tool==="demolish"){setMessage("Choose a building to clear.");return}if(land){setMessage(`${land==="forest"?"Ancient roots":land==="crag"?"Standing stones":"The mirror pond"} protect this patch.`);return}
    const item=BUILDINGS[tool];if(item.unlock>chapter+1){setMessage(`Complete chapter ${item.unlock-1} to unlock ${item.name}.`);chime("error");return}if(!canPay(resources,item.cost)){setMessage(`You still need supplies for ${item.name}.`);chime("error");return}
    rememberTown();setResources(r=>{const n={...r};Object.entries(item.cost).forEach(([k,v])=>n[k as keyof Resource]-=v!);if(tool==="cottage")n.folk+=2;return n});setBuildings(bs=>[...bs,{id:nextId.current++,kind:tool,x,y,level:1}]);setRenown(r=>r+(tool==="tower"?4:1));setMessage(`${item.name} raised.${tool==="shrine"?" The earth answers with green light.":""}`);chime(tool==="shrine"||tool==="tower"?"magic":"place");
  };
  const selectedBuilding=buildings.find(b=>b.id===inspect);
  const nearbyWellRank=selectedBuilding?Math.max(0,...buildings.filter(w=>w.kind==="well"&&withinRadius(selectedBuilding,w,WELL_RADIUS)).map(w=>w.level)):0;
  const selectedBonuses=selectedBuilding?[buildings.some(r=>r.kind==="road"&&Math.abs(r.x-selectedBuilding.x)+Math.abs(r.y-selectedBuilding.y)===1)?"Road linked · +25%":null,isMagic(selectedBuilding.x,selectedBuilding.y)&&selectedBuilding.kind==="farm"?"Enchanted soil · +4 food":null,selectedBuilding.kind==="farm"&&nearbyWellRank?`Well watered · +${nearbyWellRank*2} food`:null,selectedBuilding.kind==="lumber"&&selectedBuilding.x<4?"Forest edge · +2 wood":null,selectedBuilding.kind==="quarry"&&selectedBuilding.x>8?"Cragside · +2 stone":null].filter(Boolean):[];
  const selectedRankCopy=selectedBuilding?({cottage:"Each rank welcomes 2 folk and uses 1 food",well:"Each rank adds +2 food to nearby farms",market:"Each rank adds +8 joy",tower:"Each rank adds daily renown",farm:"Higher ranks increase harvest by 50%",lumber:"Higher ranks increase timber by 50%",quarry:"Higher ranks increase stone by 50%",shrine:"Higher ranks increase mana by 50%",road:"Roads grant adjacent producers +25% yield"} as Record<Kind,string>)[selectedBuilding.kind]:"";
  const selectedOutput=selectedBuilding?buildingProduction({kind:selectedBuilding.kind,level:selectedBuilding.level,linked:buildings.some(r=>r.kind==="road"&&Math.abs(r.x-selectedBuilding.x)+Math.abs(r.y-selectedBuilding.y)===1),morale,terrainBonus:(selectedBuilding.kind==="lumber"&&selectedBuilding.x<4)||(selectedBuilding.kind==="quarry"&&selectedBuilding.x>8),enchanted:isMagic(selectedBuilding.x,selectedBuilding.y),wellRank:nearbyWellRank}):null;
  const selectedOutputCopy=selectedBuilding&&selectedOutput?selectedBuilding.kind==="market"?`+${selectedBuilding.level*8} town joy`:selectedBuilding.kind==="well"?`+${selectedBuilding.level*2} food to nearby farms`:selectedBuilding.kind==="road"?"+25% to adjacent producers":selectedBuilding.kind==="cottage"?`Homes ${selectedBuilding.level*2} folk · ${selectedOutput.food} food/day`:Object.entries(selectedOutput).filter(([,amount])=>amount>0).map(([name,amount])=>`+${Math.floor(amount)} ${name==="glory"?"renown":name}/day`).join(" · "):"";
  const upgrade=()=>{if(!selectedBuilding||selectedBuilding.kind==="road")return;const cost={wood:12*selectedBuilding.level,stone:8*selectedBuilding.level};if(!canPay(resources,cost)){setMessage("The guild needs more wood and stone for that improvement.");chime("error");return}rememberTown();setResources(r=>({...r,wood:r.wood-cost.wood,stone:r.stone-cost.stone,folk:r.folk+(selectedBuilding.kind==="cottage"?2:0)}));setBuildings(bs=>bs.map(b=>b.id===selectedBuilding.id?{...b,level:Math.min(3,b.level+1)}:b));setRenown(r=>r+2);setMessage(`${BUILDINGS[selectedBuilding.kind].name} improved to rank ${Math.min(3,selectedBuilding.level+1)}.`);chime("success")};
  const castBloom=()=>{if(resources.mana<15){setMessage("The rite needs 15 mana.");chime("error");return}setResources(r=>({...r,mana:r.mana-15,food:r.food+28}));setEvent("The Bloom Rite ripens every field beneath a silver-green dawn.");setMessage("The valley answers: +28 food.");chime("magic")};
  useEffect(()=>{const keys=(Object.keys(BUILDINGS) as Kind[]);const onKey=(e:KeyboardEvent)=>{if(e.key==="Tab"&&(choice||showGuide||showLedger||confirmRestart||finalWin)){trapModalFocus(e);return}if(e.key==="Escape"){setInspect(null);setShowLedger(false);setShowGuide(false);setConfirmRestart(false);return}if(choice||showGuide||showLedger||confirmRestart)return;if(e.key===" "&&!(e.target instanceof HTMLButtonElement)){e.preventDefault();setPaused(p=>!p)}const n=Number(e.key);if(n>=1&&n<=keys.length&&BUILDINGS[keys[n-1]].unlock<=chapter+1)setTool(keys[n-1]);if(e.key.toLowerCase()==="b")castBloom()};window.addEventListener("keydown",onKey);return()=>window.removeEventListener("keydown",onKey)});
  const choose=(option:number)=>{if(choice==="merchant"){if(option===0){if(resources.wood<15){setMessage("The merchant needs 15 wood for that trade.");return}setResources(r=>({...r,wood:r.wood-15,stone:r.stone+22}));setEvent("The road merchant trades bright stone for seasoned timber.")}else{setResources(r=>({...r,food:r.food+18}));setRenown(r=>r+2);setEvent("The merchant feasts with the town and spreads its good name.")}}else if(choice==="spirit"){if(option===0){setResources(r=>({...r,mana:r.mana+16}));setEvent("The brook spirit leaves moonlight pooled in the wishing wells.")}else{setResources(r=>({...r,food:r.food+24}));setEvent("Wild berry hedges rise along the woodland roads.")}}else if(choice==="druid"){if(option===0){setResources(r=>({...r,wood:r.wood+30,mana:r.mana-Math.min(8,r.mana)}));setEvent("The druid wakes fallen branches without harming a living tree.")}else{setRenown(r=>r+6);setEvent("The western grove is named a sanctuary, and travelers praise the town.")}}else{if(option===0){setResources(r=>{const trade=proportionalTrade(r.wood,18,28);return{...r,wood:r.wood-trade.spent,stone:r.stone+trade.received}});setEvent("The town braces the roofs. Morning reveals storm-fallen starstone.")}else{setResources(r=>{const trade=proportionalTrade(r.food,16,24);return{...r,food:r.food-trade.spent,mana:r.mana+trade.received}});setEvent("The shrines drink the lightning. Every bell rings blue at dawn.")}}setLastVisitorDay(day);setChoice(null)};
  const fulfillRequest=()=>{const q=requests[deeds%requests.length];if(requestWait){setMessage(`The next town request arrives in ${requestWait} days.`);return}if(!canPay(resources,q.cost)){setMessage("The town stores cannot yet meet this request.");return}setResources(r=>{const n={...r};Object.entries(q.cost).forEach(([k,v])=>n[k as keyof Resource]-=v);if(deeds%3===0)n.mana+=8;if(deeds%3===1)n.food+=18;if(deeds%3===2)n.stone+=20;return n});setRenown(r=>r+[4,6,8][deeds%3]);setDeeds(d=>d+1);setNextRequestDay(day+4);setEvent(`${q.title} is fulfilled. The town’s name travels beyond the vale.`);setMessage("A promise kept is worth more than coin.")};
  const restart=()=>setConfirmRestart(true);
  const resetTown=()=>{localStorage.removeItem(SAVE_KEY);starving.current=false;setResources(INITIAL);setBuildings(START_BUILDINGS);setDay(1);setRenown(0);setChapter(0);setDeeds(0);setNextRequestDay(1);setLastVisitorDay(0);setPolicy("balanced");setEarned([]);setHistory([{day:1,text:"A soft rain has blessed the valley."}]);setLastMark(null);setInspect(null);setUndo(null);setChoice(null);setConfirmRestart(false);setWon(false);setSandbox(false);setPaused(false);setSpeed(1);setShowGuide(true);nextId.current=4;setMessage("A new glen awakens.");setEvent("A soft rain has blessed the valley.")};
  const finalWin=won&&!sandbox;
  useEffect(()=>{const open=Boolean(choice||showGuide||showLedger||confirmRestart||finalWin);if(!open){focusReturn.current?.focus();focusReturn.current=null;return}if(!focusReturn.current)focusReturn.current=document.activeElement instanceof HTMLElement&&document.activeElement!==document.body?document.activeElement:document.querySelector<HTMLButtonElement>(".day");const frame=requestAnimationFrame(()=>document.querySelector<HTMLButtonElement>(".choice-layer .ledger-close,.choice-layer .guide-card>button,.choice-layer .choice-card button:not(:disabled):not(.danger),.victory button")?.focus());return()=>cancelAnimationFrame(frame)},[choice,showGuide,showLedger,confirmRestart,finalWin]);
  const markConditions=useMemo<Record<string,boolean>>(()=>({"Green Fingers":counts.farm>=3,"Wayfinder":counts.road>=5,"Well Beloved":joy>=80,"Old Magic":counts.shrine>=2,"Promise Keeper":deeds>=3,"Vale of Legend":won}),[counts.farm,counts.road,counts.shrine,joy,deeds,won]);
  useEffect(()=>{if(!ready)return;const fresh=Object.entries(markConditions).filter(([name,done])=>done&&!earned.includes(name)).map(([name])=>name);if(!fresh.length)return;setEarned(e=>[...e,...fresh]);setLastMark(fresh[0]);chime("success")},[ready,markConditions,earned,chime]);
  useEffect(()=>{if(!lastMark)return;const t=setTimeout(()=>setLastMark(null),4200);return()=>clearTimeout(t)},[lastMark]);
  const achievements=[{name:"Green Fingers",icon:"❧",copy:"Raise three moonwheat fields"},{name:"Wayfinder",icon:"—",copy:"Lay five Lantern Roads"},{name:"Well Beloved",icon:"♡",copy:"Reach 80 town joy"},{name:"Old Magic",icon:"✦",copy:"Raise two Bloom Shrines"},{name:"Promise Keeper",icon:"◆",copy:"Fulfill three town requests"},{name:"Vale of Legend",icon:"☾",copy:"Complete the town chronicle"}].map(a=>({...a,done:earned.includes(a.name)||markConditions[a.name]}));
  const score=townScore({day,renown,joy,achievements:achievements.filter(a=>a.done).length,deeds}),townTitle=scoreTitle(score);
  const requestReady=day>=nextRequestDay&&canPay(resources,requests[deeds%requests.length].cost);
  const requestWait=requestWaitDays(day,nextRequestDay);
  const choosePolicy=(next:Policy)=>{setPolicy(next);const copy={balanced:"The council keeps hearth, field, and shrine in harmony.",harvest:"The town devotes its strength to granaries and green fields.",arcane:"The shrines burn brighter while mundane craft slows."}[next];setEvent(copy);setMessage(`${next==="balanced"?"Hearthwise":next==="harvest"?"Harvest": "Arcane"} charter adopted.`)};
  const exportChronicle=()=>{const snapshot:Save={resources,buildings,day,renown,chapter,deeds,nextRequestDay,lastVisitorDay,speed,sound,earned,history,policy,continued:sandbox},blob=new Blob([JSON.stringify(snapshot,null,2)],{type:"application/json"}),url=URL.createObjectURL(blob),link=document.createElement("a");link.href=url;link.download=`glimmerglen-day-${day}.json`;link.click();setTimeout(()=>URL.revokeObjectURL(url),0);setMessage("A copy of the town chronicle was prepared.")};
  const importChronicle=async(e:React.ChangeEvent<HTMLInputElement>)=>{const file=e.target.files?.[0];if(!file)return;try{const parsed:unknown=JSON.parse(await file.text());if(!isValidSave(parsed))throw new Error("invalid");localStorage.setItem(SAVE_KEY,JSON.stringify(parsed));window.location.reload()}catch{setShowLedger(false);setMessage("That chronicle could not be read. Your current town is unchanged.");chime("error")}finally{e.target.value=""}};
  const placementPreview=useMemo(()=>{if(!hoverTile||tool==="demolish")return null;const {x,y}=hoverTile,wellFarms=buildings.filter(b=>b.kind==="farm"&&withinRadius({x,y},b,WELL_RADIUS)).length,shrineFarms=buildings.filter(b=>b.kind==="farm"&&withinRadius({x,y},b,SHRINE_RADIUS)).length,nearbyCraft=buildings.filter(b=>["farm","lumber","quarry","shrine","tower"].includes(b.kind)&&Math.abs(b.x-x)+Math.abs(b.y-y)===1).length,wellRank=Math.max(0,...buildings.filter(b=>b.kind==="well"&&withinRadius({x,y},b,WELL_RADIUS)).map(b=>b.level));return({road:`Links ${nearbyCraft} neighboring producer${nearbyCraft===1?"":"s"}`,cottage:"Welcomes 2 folk · uses 1 food/day",farm:`Base ${4+(isMagic(x,y)?4:0)+wellRank*2} food/day before season`,lumber:`${x<4?6:4} wood/day before season`,quarry:`${x>8?5:3} stone/day`,well:`Strengthens ${wellFarms} nearby field${wellFarms===1?"":"s"}`,shrine:`Enchants ${shrineFarms} nearby field${shrineFarms===1?"":"s"} · +2 mana/day`,market:"Adds 8 town joy",tower:"Adds 5 mana and 1 renown/day"} as Record<Kind,string>)[tool]},[hoverTile,tool,buildings,isMagic]);

  return <main className={`game-shell season-${season.name.toLowerCase()}`}>
    <header className="topbar"><div className="brand"><span className="crest">G</span><div><h1>Glimmerglen</h1><p>A tiny enchanted town</p></div></div><div className="resources" aria-label="Town resources"><Resource icon="♧" label="Wood" value={resources.wood} rate={income.wood}/><Resource icon="◆" label="Stone" value={resources.stone} rate={income.stone}/><Resource icon="❧" label="Food" value={resources.food} rate={income.food} critical={resources.food===0}/><Resource icon="✦" label="Mana" value={resources.mana} rate={income.mana}/><Resource icon="♟" label="Folk" value={resources.folk} detail={`${2+ranks.cottage*2} beds`}/></div><div className="status-pair"><span className="autosave">{saved?"Chronicle saved":"Joy "+joy+"%"}</span><button className="help" onClick={()=>setShowLedger(true)} aria-label="Open town ledger">♜</button><button className="help" onClick={()=>setSound(s=>!s)} aria-label={sound?"Mute sound":"Enable sound"}>{sound?"♪":"×"}</button><button className="help" onClick={()=>setShowGuide(true)} aria-label="Open field guide">?</button><button className="speed" onClick={()=>setSpeed(s=>s===1?2:1)} aria-label="Change game speed">×{speed}</button><button className="day" onClick={()=>setPaused(p=>!p)} aria-label={paused?"Resume time":"Pause time"}><span>{season.name}</span><b>Day {day}</b><i>{paused?"▶":"Ⅱ"}</i></button></div></header>
    <section className="play-area">
      <aside className="build-panel"><div className="panel-title"><span>Builder’s folio</span><small>Choose a craft, then a meadow</small></div><div className="build-list">{(Object.keys(BUILDINGS) as Kind[]).map(kind=>{const b=BUILDINGS[kind],locked=b.unlock>chapter+1,affordable=canPay(resources,b.cost);return <button key={kind} disabled={locked} aria-pressed={tool===kind} className={`build-card ${tool===kind?"selected":""} ${locked?"locked":""} ${!locked&&!affordable?"poor":""}`} onClick={()=>setTool(kind)}><span className={`building-icon ${kind}`}>{locked?"·":b.icon}</span><span className="build-copy"><b>{b.name}</b><small>{locked?`Unlocks in chapter ${b.unlock}`:b.hint}</small><em>{Object.entries(b.cost).map(([k,v])=>`${v} ${k}`).join(" · ")}</em></span></button>})}</div><button aria-pressed={tool==="demolish"} className={`demolish ${tool==="demolish"?"active":""}`} onClick={()=>setTool("demolish")}>× Clear a building</button><div className="tip"><b>Old glen wisdom</b><p>Foresters thrive west by the trees. Stonecircles thrive east by the crags.</p></div></aside>
      <div className="world-wrap"><div className="world-head"><div><span className="eyebrow">THE GREENWARD VALE · RENOWN {renown}</span><b aria-live="polite">{message}</b>{placementPreview&&<small className="placement-preview">{BUILDINGS[tool as Kind].name} · {placementPreview}</small>}</div><button className="spell" onClick={castBloom} disabled={resources.mana<15}>✦ Bloom Rite <small>15 mana</small></button></div><div className="map living-map" role="grid" aria-label="Glimmerglen building map" style={{"--cols":COLS} as React.CSSProperties}><canvas ref={townCanvas} className="town-canvas" aria-hidden="true"/>{Array.from({length:COLS*ROWS},(_,i)=>{const x=i%COLS,y=Math.floor(i/COLS),building=buildings.find(b=>b.x===x&&b.y===y),magic=isMagic(x,y),land=terrain[key(x,y)],preview=hoverTile&&(tool==="shrine"||tool==="well")&&withinRadius(hoverTile,{x,y},tool==="shrine"?SHRINE_RADIUS:WELL_RADIUS);return <button role="gridcell" data-tile={`${x},${y}`} tabIndex={i===activeTile?0:-1} key={i} className={`tile ${magic?"magic":""} ${preview?"preview-aura":""} ${land?"wild "+land:""} ${building?"occupied":""} ${tool==="demolish"&&building?"clearable":""}`} onMouseEnter={()=>setHoverTile({x,y})} onMouseLeave={()=>setHoverTile(null)} onFocus={()=>{setHoverTile({x,y});setActiveTile(i)}} onBlur={()=>setHoverTile(null)} onKeyDown={e=>moveTileFocus(e,x,y)} onClick={()=>act(x,y)} aria-label={building?`${BUILDINGS[building.kind].name}, rank ${building.level}`:land?land:`Build ${tool==="demolish"?"nothing":BUILDINGS[tool].name} at ${x+1}, ${y+1}`}><span className="grass"/>{land&&<span className={`scenery ${land}`}>{land==="crag"?"▲":land==="pond"?"≈":"♣"}</span>}{building&&<span className={`structure ${building.kind}`}><i>{BUILDINGS[building.kind].icon}</i><small>{building.level>1?`Rank ${building.level}`:BUILDINGS[building.kind].name}</small></span>}{!building&&!land&&<span className="place-mark">+</span>}</button>})}</div><div className="event-ribbon" aria-live="polite"><span>✧</span><div><small>Word from the waystone</small><b>{event}</b></div></div></div>
      <aside className="quest-panel"><div className="chapter"><small>CHAPTER {chapter+1} OF 3</small><h2>{chapters[chapter].name}</h2><p>{chapters[chapter].copy}</p></div><div className="goals">{chapters[chapter].goals.map(g=><Goal key={g[0]} label={g[0]} value={value(g[1])} target={g[2]}/>)}</div><div className="request"><small>TOWN REQUEST · {deeds+1}</small><b>{requests[deeds%3].title}</b><p>{requests[deeds%3].copy}</p><em>{Object.entries(requests[deeds%3].cost).map(([k,v])=>`${v} ${k}`).join(" · ")} → {requests[deeds%3].reward}</em><button onClick={fulfillRequest} disabled={!requestReady}>{requestWait?`Next request in ${requestWait}d`:requestReady?"Fulfill request":"Gathering supplies…"}</button>{chapter>=1&&<div className="policy"><small>TOWN CHARTER</small><div><button aria-pressed={policy==="balanced"} className={policy==="balanced"?"active":""} onClick={()=>choosePolicy("balanced")} title="+4 joy">Hearth</button><button aria-pressed={policy==="harvest"} className={policy==="harvest"?"active":""} onClick={()=>choosePolicy("harvest")} title="+25% food">Harvest</button><button aria-pressed={policy==="arcane"} className={policy==="arcane"?"active":""} onClick={()=>choosePolicy("arcane")} title="+30% mana, -10% wood and stone">Arcane</button></div></div>}</div><div className="town-stats"><span><small>Buildings</small><b>{buildings.length}</b></span><span><small>Joy</small><b>{joy}%</b></span><span><small>Renown</small><b>{renown}</b></span></div><div className={`spirit ${morale>1?"high":morale<1?"low":""}`}><b>Town spirit</b><span>{morale>1?"Joyful · all craft +10%":morale<1?"Troubled · all craft −20%":"Steady · normal production"}</span></div><div className="season-note"><b>{season.name}</b><span>Food ×{season.food} · Wood ×{season.wood}</span></div>{nextVisitor&&<div className="visitor-forecast"><span>✧</span><small>Next waystone visitor</small><b>in {nextVisitor-day} days</b></div>}<button className="restart" onClick={restart}>Begin a new glen</button></aside>
    </section>
    {undo&&<button className="undo-toast" onClick={undoLast} aria-label="Undo last town change"><span>↶</span><b>Undo last change</b><small>Available for 7 seconds</small></button>}
    {lastMark&&<div className="mark-toast" role="status"><span>✦</span><small>NEW MARK IN THE LEDGER</small><b>{lastMark}</b></div>}
    {selectedBuilding&&<div className="inspect-card" role="dialog" aria-label={`${BUILDINGS[selectedBuilding.kind].name} details`}><button className="close" onClick={()=>setInspect(null)} aria-label="Close building details">×</button><span className={`building-icon ${selectedBuilding.kind}`}>{BUILDINGS[selectedBuilding.kind].icon}</span><small>TOWN LEDGER</small><h3>{BUILDINGS[selectedBuilding.kind].name}</h3><p>{BUILDINGS[selectedBuilding.kind].hint}</p>{selectedOutputCopy&&<div className="output-line"><small>CURRENT CONTRIBUTION</small><b>{selectedOutputCopy}</b></div>}{selectedBonuses.length>0&&<div className="bonus-list">{selectedBonuses.map(b=><span key={b}>✦ {b}</span>)}</div>}<div className="rank"><b>{selectedBuilding.kind==="road"?"Road craft":`Rank ${selectedBuilding.level} of 3`}</b><small>{selectedRankCopy}</small></div>{selectedBuilding.kind!=="road"&&<button onClick={upgrade} disabled={selectedBuilding.level>=3}>{selectedBuilding.level>=3?"Masterwork complete":`Improve · ${12*selectedBuilding.level} wood · ${8*selectedBuilding.level} stone`}</button>}</div>}
    {choice&&<div className="choice-layer" role="dialog" aria-modal="true" aria-label="Town event"><EventChoice kind={choice} choose={choose} canTrade={resources.wood>=15}/></div>}
    {confirmRestart&&<div className="choice-layer" role="dialog" aria-modal="true" aria-labelledby="restart-title"><div className="choice-card restart-card"><span>↺</span><small>A BLANK PAGE IN THE CHRONICLE</small><h2 id="restart-title">Begin a new glen?</h2><p>Your current town and every mark it earned will be cleared from this browser.</p><button className="danger" onClick={resetTown}>Yes, begin anew</button><button onClick={()=>setConfirmRestart(false)}>Keep tending this town</button></div></div>}
    {showGuide&&<div className="choice-layer" role="dialog" aria-modal="true" aria-labelledby="guide-title"><div className="guide-card"><span className="guide-seal">G</span><small>THE GREENWARD FIELD GUIDE</small><h2 id="guide-title">Three ways to make the vale flourish</h2><div className="guide-steps"><div><b>1</b><h3>Read the land</h3><p>Foresters favor western trees. Quarries favor eastern crags. Magic doubles moonwheat.</p></div><div><b>2</b><h3>Connect the craft</h3><p>Place Lantern Roads beside producers for 25% more yield. Wells strengthen nearby farms.</p></div><div><b>3</b><h3>Follow the chronicle</h3><p>Complete chapter goals to unlock markets and the Starwatch Tower. Your town saves itself.</p></div></div><div className="guide-keys"><span><kbd>1–9</kbd> choose craft</span><span><kbd>Arrows</kbd> cross map</span><span><kbd>Space</kbd> pause</span><span><kbd>B</kbd> Bloom Rite</span><span><kbd>Esc</kbd> close panels</span></div><button onClick={()=>setShowGuide(false)}>Open the builder’s folio</button></div></div>}
    {showLedger&&<div className="choice-layer" role="dialog" aria-modal="true" aria-labelledby="ledger-title"><div className="ledger-card"><button className="ledger-close" onClick={()=>setShowLedger(false)} aria-label="Close town ledger">×</button><small>THE TOWN LEDGER</small><h2 id="ledger-title">Marks in the margin</h2><p>Small deeds become the stories travelers carry beyond the vale.</p><div className="ledger-columns"><div className="achievement-grid">{achievements.map(a=><div key={a.name} className={a.done?"earned":""}><span>{a.done?a.icon:"?"}</span><b>{a.name}</b><small>{a.copy}</small></div>)}</div><div className="chronicle-list"><small>RECENT CHRONICLE</small>{[...history].reverse().map((entry,i)=><div key={`${entry.day}-${i}`}><b>Day {entry.day}</b><span>{entry.text}</span></div>)}</div></div><div className="ledger-summary"><span><b>{achievements.filter(a=>a.done).length}/6</b> marks earned</span><span><b>{deeds}</b> promises kept</span><span><b>{day}</b> days tended</span><span><b>{score}</b> town score</span></div><div className="ledger-title">Current rank · {townTitle}</div><div className="ledger-files"><button onClick={exportChronicle}>Save a chronicle copy</button><div role="button" tabIndex={0} onKeyDown={e=>{if(e.key==="Enter"||e.key===" "){e.preventDefault();e.currentTarget.querySelector("input")?.click()}}}>Restore a chronicle<input aria-hidden="true" tabIndex={-1} type="file" accept="application/json,.json" onChange={importChronicle}/></div></div></div></div>}
    {finalWin&&<div className="victory" role="dialog" aria-modal="true" aria-labelledby="victory-title"><div className="victory-card"><span>✦</span><small>THE VALE REMEMBERS</small><h2 id="victory-title">Glimmerglen awakens</h2><p>Your folk have woven craft, fellowship, and old magic into a woodland haven worthy of legend.</p><div className="victory-rank"><small>TOWN RANK</small><b>{townTitle}</b><span>{score.toLocaleString()} points</span></div><div className="victory-stats"><b>{day}<small>days</small></b><b>{resources.folk}<small>folk</small></b><b>{renown}<small>renown</small></b></div><div className="victory-actions"><button onClick={()=>{setSandbox(true);setMessage("The chronicle is complete, but the vale may keep growing.")}}>Keep tending the vale</button><button className="secondary" onClick={resetTown}>Grow another town</button></div></div></div>}
  </main>
}
function Resource({icon,label,value,rate,detail,critical=false}:{icon:string;label:string;value:number;rate?:number;detail?:string;critical?:boolean}){return <div className={`resource ${critical?"critical":""}`} aria-label={`${label}: ${value}${rate!==undefined?`, ${rate>=0?"plus ":"minus "}${Math.abs(rate)} per day`:""}${detail?`, ${detail}`:""}`}><span aria-hidden="true">{icon}</span><div><small>{label}</small><b>{value.toLocaleString()}</b></div>{rate!==undefined&&<em className={rate<0?"negative":""}>{rate>=0?"+":""}{rate.toLocaleString()}/day</em>}{detail&&<em>{detail}</em>}</div>}
function Goal({label,value,target}:{label:string;value:number;target:number}){const done=value>=target;return <div className={`goal ${done?"done":""}`}><span>{done?"✓":""}</span><div><b>{label}</b><i><em style={{width:`${Math.min(100,value/target*100)}%`}}/></i></div><small>{Math.min(value,target)}/{target}</small></div>}
function EventChoice({kind,choose,canTrade}:{kind:"merchant"|"spirit"|"druid"|"storm";choose:(n:number)=>void;canTrade:boolean}){const content={merchant:{icon:"¤",label:"A TRAVELER AT THE WAYSTONE",title:"The Lantern Merchant",copy:"A road-worn trader offers a bargain, but seems even more interested in your supper fire.",a:"Trade 15 wood for 22 stone",b:"Share supper: +18 food, +2 renown"},spirit:{icon:"✦",label:"A VOICE UPON THE WATER",title:"The Spirit of Stillwater",copy:"A river-bright spirit asks what blessing the young town needs most.",a:"Ask for 16 mana",b:"Ask for 24 food"},druid:{icon:"♧",label:"A KEEPER OF OLD ROOTS",title:"The Druid of Greenward",copy:"The western grove has awakened. Its keeper asks whether it should serve the town or remain untouched.",a:"Gather fallen wood: +30 wood, up to −8 mana",b:"Name a sanctuary: +6 renown"},storm:{icon:"☾",label:"THUNDER BEYOND THE CRAGS",title:"The Starstorm",copy:"Blue lightning walks down from the mountains. The town can brace its roofs or invite the storm into its shrines.",a:"Brace with up to 18 wood for up to 28 stone",b:"Offer up to 16 food for up to 24 mana"}}[kind];const firstDisabled=kind==="merchant"&&!canTrade;return <div className="choice-card"><span>{content.icon}</span><small>{content.label}</small><h2>{content.title}</h2><p>{content.copy}</p><button onClick={()=>choose(0)} disabled={firstDisabled}>{firstDisabled?"Need 15 wood to trade":content.a}</button><button onClick={()=>choose(1)}>{content.b}</button></div>}
