/* eslint-disable react-hooks/set-state-in-effect */
"use client";

import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import "./game.css";
import { calculateJoy, canAfford, isValidSave, moraleMultiplier, roadMultiplier, scoreTitle, townScore } from "./game-model";

type Resource = { wood:number; stone:number; food:number; mana:number; folk:number };
type Kind = "road"|"cottage"|"farm"|"lumber"|"quarry"|"well"|"shrine"|"market"|"tower";
type Tool = Kind|"demolish";
type Building = { id:number; kind:Kind; x:number; y:number; level:number };
type Save = { resources:Resource; buildings:Building[]; day:number; renown:number; chapter:number; deeds?:number; speed?:1|2; sound?:boolean };
type UndoState = { resources:Resource; buildings:Building[]; renown:number; message:string };

const COLS=12, ROWS=8, SAVE_KEY="glimmerglen-save-v2";
const BUILDINGS:Record<Kind,{name:string;icon:string;cost:Partial<Resource>;hint:string;unlock:number;refund:Partial<Resource>}>= {
  road:{name:"Lantern Road",icon:"—",cost:{wood:2},refund:{wood:1},hint:"Connects neighboring workshops",unlock:1},
  cottage:{name:"Moss Cottage",icon:"⌂",cost:{wood:16,stone:6},refund:{wood:8,stone:3},hint:"Homes 2 folk · uses 1 food",unlock:1},
  farm:{name:"Moonwheat Field",icon:"≋",cost:{wood:10},refund:{wood:5},hint:"4 food · doubled by magic",unlock:1},
  lumber:{name:"Forester Lodge",icon:"♧",cost:{wood:8,stone:3},refund:{wood:4,stone:1},hint:"4 wood · +2 by forest",unlock:1},
  quarry:{name:"Stonecircle",icon:"◆",cost:{wood:10},refund:{wood:5},hint:"3 stone · +2 by crags",unlock:1},
  well:{name:"Wishing Well",icon:"◉",cost:{stone:14},refund:{stone:7},hint:"Adds 2 food to close farms",unlock:1},
  shrine:{name:"Bloom Shrine",icon:"✦",cost:{wood:18,stone:12},refund:{wood:9,stone:6},hint:"2 mana · enchants nearby land",unlock:1},
  market:{name:"Lantern Market",icon:"¤",cost:{wood:24,stone:10},refund:{wood:12,stone:5},hint:"Raises joy near cottages",unlock:2},
  tower:{name:"Starwatch Tower",icon:"☾",cost:{stone:28,mana:12},refund:{stone:14},hint:"5 mana · raises renown",unlock:3},
};
const START_BUILDINGS:Building[]=[{id:1,kind:"cottage",x:5,y:4,level:1},{id:2,kind:"farm",x:4,y:4,level:1},{id:3,kind:"lumber",x:3,y:2,level:1}];
const INITIAL:Resource={wood:52,stone:30,food:38,mana:0,folk:4};
const terrain:Record<string,"forest"|"crag"|"pond">={"0,0":"forest","1,0":"forest","0,1":"forest","6,0":"forest","2,6":"forest","2,7":"forest","3,7":"forest","10,0":"crag","11,0":"crag","11,1":"crag","9,6":"crag","10,6":"crag","10,7":"crag","11,7":"crag","1,5":"pond"};
const seasons=[{name:"Dewspring",food:1.2,wood:1},{name:"Suncrest",food:1.35,wood:.9},{name:"Amberfall",food:1,wood:1.3},{name:"Frostwane",food:.7,wood:1}];
const requests=[
  {title:"Pilgrims at the south road",copy:"Send provisions for their onward journey.",cost:{food:24},reward:"+4 renown · +8 mana"},
  {title:"The bridgewright’s levy",copy:"Timber will reopen the old crossing.",cost:{wood:30,stone:8},reward:"+6 renown · +18 food"},
  {title:"Star charts for the academy",copy:"Lend mana to the hilltop astronomers.",cost:{mana:22},reward:"+8 renown · +20 stone"},
] as const;
const chapters=[
  {name:"Wake the sleeping vale",copy:"Build a home where magic and mortal craft flourish together.",goals:[["Welcome 10 folk","folk",10],["Store 60 food","food",60],["Gather 20 mana","mana",20]] as const},
  {name:"Light the woodland roads",copy:"A true town needs fellowship, trade, and warm lanterns after dusk.",goals:[["Welcome 16 folk","folk",16],["Earn 12 renown","renown",12],["Raise a Lantern Market","market",1]] as const},
  {name:"Read the crown of stars",copy:"Build a landmark worthy of the old stories and make the valley sing.",goals:[["Raise a Starwatch Tower","tower",1],["Gather 50 mana","mana",50],["Reach 85 joy","joy",85]] as const},
];

const key=(x:number,y:number)=>`${x},${y}`;
const near=(a:{x:number;y:number},b:{x:number;y:number},r=2)=>Math.hypot(a.x-b.x,a.y-b.y)<=r;
const canPay=(r:Resource,c:Partial<Resource>)=>canAfford(r,c as Record<string,number>);

export default function Home(){
  const [resources,setResources]=useState(INITIAL),[buildings,setBuildings]=useState<Building[]>(START_BUILDINGS);
  const [tool,setTool]=useState<Tool>("farm"),[day,setDay]=useState(1),[paused,setPaused]=useState(false);
  const [message,setMessage]=useState("The glen is waiting. Choose a craft from the folio."),[event,setEvent]=useState("A soft rain has blessed the valley.");
  const [renown,setRenown]=useState(0),[chapter,setChapter]=useState(0),[deeds,setDeeds]=useState(0),[inspect,setInspect]=useState<number|null>(null),[saved,setSaved]=useState(false),[ready,setReady]=useState(false);
  const [choice,setChoice]=useState<null|"merchant"|"spirit"|"druid"|"storm">(null),[showGuide,setShowGuide]=useState(true),[speed,setSpeed]=useState<1|2>(1),[hoverTile,setHoverTile]=useState<{x:number;y:number}|null>(null),nextId=useRef(4);
  const [sound,setSound]=useState(true),[showLedger,setShowLedger]=useState(false),[undo,setUndo]=useState<UndoState|null>(null);
  const chime=useCallback((tone:"place"|"magic"|"success"|"error"="place")=>{if(!sound)return;try{const AudioCtx=window.AudioContext||(window as typeof window&{webkitAudioContext:typeof AudioContext}).webkitAudioContext;const ctx=new AudioCtx(),osc=ctx.createOscillator(),gain=ctx.createGain();osc.type=tone==="error"?"sawtooth":"sine";osc.frequency.value={place:392,magic:659,success:523,error:180}[tone];gain.gain.setValueAtTime(.05,ctx.currentTime);gain.gain.exponentialRampToValueAtTime(.001,ctx.currentTime+.25);osc.connect(gain);gain.connect(ctx.destination);osc.start();osc.stop(ctx.currentTime+.26);osc.addEventListener("ended",()=>ctx.close())}catch{/* Audio is optional; unsupported browsers remain silent. */}},[sound]);

  useEffect(()=>{try{const raw=localStorage.getItem(SAVE_KEY);if(raw){const parsed:unknown=JSON.parse(raw);if(isValidSave(parsed)){const s=parsed as Save;setResources(s.resources);setBuildings(s.buildings);setDay(s.day);setRenown(s.renown);setChapter(s.chapter);setDeeds(s.deeds??0);setSpeed(s.speed??1);setSound(s.sound??true);nextId.current=Math.max(...s.buildings.map(b=>b.id),0)+1;setMessage("Welcome back. The glen remembered your care.");setShowGuide(false)}else{localStorage.removeItem(SAVE_KEY);setMessage("A damaged chronicle was set aside. A fresh glen awaits.")}}}catch{localStorage.removeItem(SAVE_KEY);setMessage("A damaged chronicle was set aside. A fresh glen awaits.")}setReady(true)},[]);
  useEffect(()=>{if(!ready)return;const t=setTimeout(()=>{localStorage.setItem(SAVE_KEY,JSON.stringify({resources,buildings,day,renown,chapter,deeds,speed,sound}));setSaved(true);setTimeout(()=>setSaved(false),900)},600);return()=>clearTimeout(t)},[resources,buildings,day,renown,chapter,deeds,speed,sound,ready]);

  const season=seasons[Math.floor((day-1)/8)%4];
  const rememberTown=()=>setUndo({resources:{...resources},buildings:buildings.map(b=>({...b})),renown,message});
  const undoLast=()=>{if(!undo)return;setResources(undo.resources);setBuildings(undo.buildings);setRenown(undo.renown);setMessage(`Undone: ${undo.message}`);setInspect(null);nextId.current=Math.max(...undo.buildings.map(b=>b.id),0)+1;setUndo(null);chime("place")};
  const isMagic=useCallback((x:number,y:number)=>buildings.some(b=>b.kind==="shrine"&&near({x,y},b,2.3)),[buildings]);
  const counts=useMemo(()=>Object.fromEntries(Object.keys(BUILDINGS).map(k=>[k,buildings.filter(b=>b.kind===k).length])) as Record<Kind,number>,[buildings]);
  const joy=useMemo(()=>calculateJoy({shrines:counts.shrine,markets:counts.market,wells:counts.well,roads:counts.road,food:resources.food,folk:resources.folk,cottages:counts.cottage}),[counts,resources]);
  const morale=moraleMultiplier(joy);
  const income=useMemo(()=>{let wood=1,stone=0,food=0,mana=0,glory=0;buildings.forEach(b=>{const lv=1+(b.level-1)*.5,linked=buildings.some(r=>r.kind==="road"&&Math.abs(r.x-b.x)+Math.abs(r.y-b.y)===1),flow=roadMultiplier(linked)*morale;if(b.kind==="lumber")wood+=(4+(b.x<4?2:0))*lv*flow;if(b.kind==="quarry")stone+=(3+(b.x>8?2:0))*lv*flow;if(b.kind==="farm")food+=(4+(isMagic(b.x,b.y)?4:0)+(buildings.some(w=>w.kind==="well"&&near(b,w,2))?2:0))*lv*flow;if(b.kind==="shrine")mana+=2*lv*flow;if(b.kind==="tower"){mana+=5*lv*flow;glory+=1}if(b.kind==="cottage")food-=1});return{wood:Math.floor(wood*season.wood),stone:Math.floor(stone),food:Math.floor(food*season.food),mana:Math.floor(mana),glory}},[buildings,isMagic,season,morale]);

  useEffect(()=>{if(paused||choice||showGuide||showLedger||undo)return;const t=setInterval(()=>{setDay(d=>d+1);setResources(r=>{const food=Math.max(0,r.food+income.food);return{wood:r.wood+income.wood,stone:r.stone+income.stone,food,mana:r.mana+income.mana,folk:food===0&&r.folk>2?r.folk-1:r.folk}});if(income.glory)setRenown(v=>v+income.glory)},2400/speed);return()=>clearInterval(t)},[paused,choice,showGuide,showLedger,undo,income,speed]);
  useEffect(()=>{if(!undo)return;const t=setTimeout(()=>setUndo(null),7000);return()=>clearTimeout(t)},[undo]);
  useEffect(()=>{if(day===7)setChoice("merchant");if(day===15)setChoice("spirit");if(day===23)setChoice("druid");if(day===31)setChoice("storm");if(day%8===1&&day>1)setEvent(`${season.name} settles over the valley. The harvest rhythm has changed.`)},[day,season.name]);

  const value=(metric:string)=>metric==="renown"?renown:metric==="joy"?joy:metric in counts?counts[metric as Kind]:resources[metric as keyof Resource];
  const chapterDone=chapters[chapter].goals.every(g=>value(g[1])>=g[2]);
  useEffect(()=>{if(chapterDone&&chapter<2){setChapter(c=>c+1);setRenown(r=>r+5);setEvent("A new chapter opens in the town chronicle.");setMessage("The valley has taken notice. New craft is now unlocked.")}},[chapterDone,chapter]);

  const act=(x:number,y:number)=>{
    const existing=buildings.find(b=>b.x===x&&b.y===y),land=terrain[key(x,y)];
    if(existing){if(tool==="demolish"){rememberTown();const refund=BUILDINGS[existing.kind].refund;setBuildings(bs=>bs.filter(b=>b.id!==existing.id));setResources(r=>{const n={...r};Object.entries(refund).forEach(([k,v])=>n[k as keyof Resource]+=v!);if(existing.kind==="cottage")n.folk=Math.max(2,n.folk-2);return n});setMessage(`${BUILDINGS[existing.kind].name} cleared. Half its materials were recovered.`);setInspect(null);chime("place")}else setInspect(existing.id);return}
    if(tool==="demolish"){setMessage("Choose a building to clear.");return}if(land){setMessage(`${land==="forest"?"Ancient roots":land==="crag"?"Standing stones":"The mirror pond"} protect this patch.`);return}
    const item=BUILDINGS[tool];if(item.unlock>chapter+1){setMessage(`Complete chapter ${item.unlock-1} to unlock ${item.name}.`);chime("error");return}if(!canPay(resources,item.cost)){setMessage(`You still need supplies for ${item.name}.`);chime("error");return}
    rememberTown();setResources(r=>{const n={...r};Object.entries(item.cost).forEach(([k,v])=>n[k as keyof Resource]-=v!);if(tool==="cottage")n.folk+=2;return n});setBuildings(bs=>[...bs,{id:nextId.current++,kind:tool,x,y,level:1}]);setRenown(r=>r+(tool==="tower"?4:1));setMessage(`${item.name} raised.${tool==="shrine"?" The earth answers with green light.":""}`);chime(tool==="shrine"||tool==="tower"?"magic":"place");
  };
  const selectedBuilding=buildings.find(b=>b.id===inspect);
  const selectedBonuses=selectedBuilding?[buildings.some(r=>r.kind==="road"&&Math.abs(r.x-selectedBuilding.x)+Math.abs(r.y-selectedBuilding.y)===1)?"Road linked · +25%":null,isMagic(selectedBuilding.x,selectedBuilding.y)&&selectedBuilding.kind==="farm"?"Enchanted soil · +4 food":null,selectedBuilding.kind==="farm"&&buildings.some(w=>w.kind==="well"&&near(selectedBuilding,w,2))?"Well watered · +2 food":null,selectedBuilding.kind==="lumber"&&selectedBuilding.x<4?"Forest edge · +2 wood":null,selectedBuilding.kind==="quarry"&&selectedBuilding.x>8?"Cragside · +2 stone":null].filter(Boolean):[];
  const upgrade=()=>{if(!selectedBuilding||selectedBuilding.kind==="road")return;const cost={wood:12*selectedBuilding.level,stone:8*selectedBuilding.level};if(!canPay(resources,cost)){setMessage("The guild needs more wood and stone for that improvement.");return}rememberTown();setResources(r=>({...r,wood:r.wood-cost.wood,stone:r.stone-cost.stone}));setBuildings(bs=>bs.map(b=>b.id===selectedBuilding.id?{...b,level:Math.min(3,b.level+1)}:b));setRenown(r=>r+2);setMessage(`${BUILDINGS[selectedBuilding.kind].name} improved to rank ${Math.min(3,selectedBuilding.level+1)}.`)};
  const castBloom=()=>{if(resources.mana<15){setMessage("The rite needs 15 mana.");chime("error");return}setResources(r=>({...r,mana:r.mana-15,food:r.food+28}));setEvent("The Bloom Rite ripens every field beneath a silver-green dawn.");setMessage("The valley answers: +28 food.");chime("magic")};
  useEffect(()=>{const keys=(Object.keys(BUILDINGS) as Kind[]);const onKey=(e:KeyboardEvent)=>{if(e.key==="Escape"){setInspect(null);setShowLedger(false);return}if(e.key===" "&&!(e.target instanceof HTMLButtonElement)){e.preventDefault();setPaused(p=>!p)}const n=Number(e.key);if(n>=1&&n<=keys.length&&BUILDINGS[keys[n-1]].unlock<=chapter+1)setTool(keys[n-1]);if(e.key.toLowerCase()==="b")castBloom()};window.addEventListener("keydown",onKey);return()=>window.removeEventListener("keydown",onKey)});
  const choose=(option:number)=>{if(choice==="merchant"){if(option===0){if(resources.wood<15){setMessage("The merchant needs 15 wood for that trade.");return}setResources(r=>({...r,wood:r.wood-15,stone:r.stone+22}));setEvent("The road merchant trades bright stone for seasoned timber.")}else{setResources(r=>({...r,food:r.food+18}));setRenown(r=>r+2);setEvent("The merchant feasts with the town and spreads its good name.")}}else if(choice==="spirit"){if(option===0){setResources(r=>({...r,mana:r.mana+16}));setEvent("The brook spirit leaves moonlight pooled in the wishing wells.")}else{setResources(r=>({...r,food:r.food+24}));setEvent("Wild berry hedges rise along the woodland roads.")}}else if(choice==="druid"){if(option===0){setResources(r=>({...r,wood:r.wood+30,mana:r.mana-Math.min(8,r.mana)}));setEvent("The druid wakes fallen branches without harming a living tree.")}else{setRenown(r=>r+6);setEvent("The western grove is named a sanctuary, and travelers praise the town.")}}else{if(option===0){setResources(r=>({...r,wood:Math.max(0,r.wood-18),stone:r.stone+28}));setEvent("The town braces the roofs. Morning reveals storm-fallen starstone.")}else{setResources(r=>({...r,food:Math.max(0,r.food-16),mana:r.mana+24}));setEvent("The shrines drink the lightning. Every bell rings blue at dawn.")}}setChoice(null)};
  const fulfillRequest=()=>{const q=requests[deeds%requests.length];if(!canPay(resources,q.cost)){setMessage("The town stores cannot yet meet this request.");return}setResources(r=>{const n={...r};Object.entries(q.cost).forEach(([k,v])=>n[k as keyof Resource]-=v);if(deeds%3===0)n.mana+=8;if(deeds%3===1)n.food+=18;if(deeds%3===2)n.stone+=20;return n});setRenown(r=>r+[4,6,8][deeds%3]);setDeeds(d=>d+1);setEvent(`${q.title} is fulfilled. The town’s name travels beyond the vale.`);setMessage("A promise kept is worth more than coin.")};
  const restart=()=>{localStorage.removeItem(SAVE_KEY);setResources(INITIAL);setBuildings(START_BUILDINGS);setDay(1);setRenown(0);setChapter(0);setDeeds(0);setInspect(null);setUndo(null);setChoice(null);setPaused(false);setSpeed(1);setShowGuide(true);nextId.current=4;setMessage("A new glen awakens.");setEvent("A soft rain has blessed the valley.")};
  const finalWin=chapter===2&&chapterDone;
  const achievements=[{name:"Green Fingers",icon:"❧",done:counts.farm>=3,copy:"Raise three moonwheat fields"},{name:"Wayfinder",icon:"—",done:counts.road>=5,copy:"Lay five Lantern Roads"},{name:"Well Beloved",icon:"♡",done:joy>=80,copy:"Reach 80 town joy"},{name:"Old Magic",icon:"✦",done:counts.shrine>=2,copy:"Raise two Bloom Shrines"},{name:"Promise Keeper",icon:"◆",done:deeds>=3,copy:"Fulfill three town requests"},{name:"Vale of Legend",icon:"☾",done:finalWin,copy:"Complete the town chronicle"}];
  const score=townScore({day,renown,joy,achievements:achievements.filter(a=>a.done).length,deeds}),townTitle=scoreTitle(score);

  return <main className={`game-shell season-${season.name.toLowerCase()}`}>
    <header className="topbar"><div className="brand"><span className="crest">G</span><div><h1>Glimmerglen</h1><p>A tiny enchanted town</p></div></div><div className="resources" aria-label="Town resources"><Resource icon="♧" label="Wood" value={resources.wood} rate={income.wood}/><Resource icon="◆" label="Stone" value={resources.stone} rate={income.stone}/><Resource icon="❧" label="Food" value={resources.food} rate={income.food}/><Resource icon="✦" label="Mana" value={resources.mana} rate={income.mana}/><Resource icon="♟" label="Folk" value={resources.folk}/></div><div className="status-pair"><span className="autosave">{saved?"Chronicle saved":"Joy "+joy+"%"}</span><button className="help" onClick={()=>setShowLedger(true)} aria-label="Open town ledger">♜</button><button className="help" onClick={()=>setSound(s=>!s)} aria-label={sound?"Mute sound":"Enable sound"}>{sound?"♪":"×"}</button><button className="help" onClick={()=>setShowGuide(true)} aria-label="Open field guide">?</button><button className="speed" onClick={()=>setSpeed(s=>s===1?2:1)} aria-label="Change game speed">×{speed}</button><button className="day" onClick={()=>setPaused(p=>!p)} aria-label={paused?"Resume time":"Pause time"}><span>{season.name}</span><b>Day {day}</b><i>{paused?"▶":"Ⅱ"}</i></button></div></header>
    <section className="play-area">
      <aside className="build-panel"><div className="panel-title"><span>Builder’s folio</span><small>Choose a craft, then a meadow</small></div><div className="build-list">{(Object.keys(BUILDINGS) as Kind[]).map(kind=>{const b=BUILDINGS[kind],locked=b.unlock>chapter+1,affordable=canPay(resources,b.cost);return <button key={kind} disabled={locked} className={`build-card ${tool===kind?"selected":""} ${locked?"locked":""} ${!locked&&!affordable?"poor":""}`} onClick={()=>setTool(kind)}><span className={`building-icon ${kind}`}>{locked?"·":b.icon}</span><span className="build-copy"><b>{b.name}</b><small>{locked?`Unlocks in chapter ${b.unlock}`:b.hint}</small><em>{Object.entries(b.cost).map(([k,v])=>`${v} ${k}`).join(" · ")}</em></span></button>})}</div><button className={`demolish ${tool==="demolish"?"active":""}`} onClick={()=>setTool("demolish")}>× Clear a building</button><div className="tip"><b>Old glen wisdom</b><p>Foresters thrive west by the trees. Stonecircles thrive east by the crags.</p></div></aside>
      <div className="world-wrap"><div className="world-head"><div><span className="eyebrow">THE GREENWARD VALE · RENOWN {renown}</span><b aria-live="polite">{message}</b></div><button className="spell" onClick={castBloom} disabled={resources.mana<15}>✦ Bloom Rite <small>15 mana</small></button></div><div className="map" role="grid" aria-label="Glimmerglen building map" style={{"--cols":COLS} as React.CSSProperties}>{Array.from({length:COLS*ROWS},(_,i)=>{const x=i%COLS,y=Math.floor(i/COLS),building=buildings.find(b=>b.x===x&&b.y===y),magic=isMagic(x,y),land=terrain[key(x,y)],preview=hoverTile&&(tool==="shrine"||tool==="well")&&Math.hypot(hoverTile.x-x,hoverTile.y-y)<=2.3;return <button role="gridcell" key={i} className={`tile ${magic?"magic":""} ${preview?"preview-aura":""} ${land?"wild "+land:""} ${building?"occupied":""} ${tool==="demolish"&&building?"clearable":""}`} onMouseEnter={()=>setHoverTile({x,y})} onMouseLeave={()=>setHoverTile(null)} onFocus={()=>setHoverTile({x,y})} onBlur={()=>setHoverTile(null)} onClick={()=>act(x,y)} aria-label={building?`${BUILDINGS[building.kind].name}, rank ${building.level}`:land?land:`Build ${tool==="demolish"?"nothing":BUILDINGS[tool].name} at ${x+1}, ${y+1}`}><span className="grass"/>{land&&<span className={`scenery ${land}`}>{land==="crag"?"▲":land==="pond"?"≈":"♣"}</span>}{building&&<span className={`structure ${building.kind}`}><i>{BUILDINGS[building.kind].icon}</i><small>{building.level>1?`Rank ${building.level}`:BUILDINGS[building.kind].name}</small></span>}{!building&&!land&&<span className="place-mark">+</span>}</button>})}{Array.from({length:Math.min(resources.folk,10)},(_,i)=><span key={i} className={`villager v${i%8}`} title="Glimmerfolk">●<i/></span>)}</div><div className="event-ribbon" aria-live="polite"><span>✧</span><div><small>Word from the waystone</small><b>{event}</b></div></div></div>
      <aside className="quest-panel"><div className="chapter"><small>CHAPTER {chapter+1} OF 3</small><h2>{chapters[chapter].name}</h2><p>{chapters[chapter].copy}</p></div><div className="goals">{chapters[chapter].goals.map(g=><Goal key={g[0]} label={g[0]} value={value(g[1])} target={g[2]}/>)}</div><div className="request"><small>TOWN REQUEST · {deeds+1}</small><b>{requests[deeds%3].title}</b><p>{requests[deeds%3].copy}</p><em>{Object.entries(requests[deeds%3].cost).map(([k,v])=>`${v} ${k}`).join(" · ")} → {requests[deeds%3].reward}</em><button onClick={fulfillRequest}>Fulfill request</button></div><div className="town-stats"><span><small>Buildings</small><b>{buildings.length}</b></span><span><small>Joy</small><b>{joy}%</b></span><span><small>Renown</small><b>{renown}</b></span></div><div className={`spirit ${morale>1?"high":morale<1?"low":""}`}><b>Town spirit</b><span>{morale>1?"Joyful · all craft +10%":morale<1?"Troubled · all craft −20%":"Steady · normal production"}</span></div><div className="season-note"><b>{season.name}</b><span>Food ×{season.food} · Wood ×{season.wood}</span></div><button className="restart" onClick={restart}>Begin a new glen</button></aside>
    </section>
    {undo&&<button className="undo-toast" onClick={undoLast} aria-label="Undo last town change"><span>↶</span><b>Undo last change</b><small>Available for 7 seconds</small></button>}
    {selectedBuilding&&<div className="inspect-card"><button className="close" onClick={()=>setInspect(null)}>×</button><span className={`building-icon ${selectedBuilding.kind}`}>{BUILDINGS[selectedBuilding.kind].icon}</span><small>TOWN LEDGER</small><h3>{BUILDINGS[selectedBuilding.kind].name}</h3><p>{BUILDINGS[selectedBuilding.kind].hint}</p>{selectedBonuses.length>0&&<div className="bonus-list">{selectedBonuses.map(b=><span key={b}>✦ {b}</span>)}</div>}<div className="rank">{selectedBuilding.kind==="road"?"Roads grant adjacent producers +25% yield":`Rank ${selectedBuilding.level} of 3`}</div>{selectedBuilding.kind!=="road"&&<button onClick={upgrade} disabled={selectedBuilding.level>=3}>{selectedBuilding.level>=3?"Masterwork complete":`Improve · ${12*selectedBuilding.level} wood · ${8*selectedBuilding.level} stone`}</button>}</div>}
    {choice&&<div className="choice-layer" role="dialog" aria-modal="true" aria-label="Town event"><EventChoice kind={choice} choose={choose}/></div>}
    {showGuide&&<div className="choice-layer" role="dialog" aria-modal="true" aria-labelledby="guide-title"><div className="guide-card"><span className="guide-seal">G</span><small>THE GREENWARD FIELD GUIDE</small><h2 id="guide-title">Three ways to make the vale flourish</h2><div className="guide-steps"><div><b>1</b><h3>Read the land</h3><p>Foresters favor western trees. Quarries favor eastern crags. Magic doubles moonwheat.</p></div><div><b>2</b><h3>Connect the craft</h3><p>Place Lantern Roads beside producers for 25% more yield. Wells strengthen nearby farms.</p></div><div><b>3</b><h3>Follow the chronicle</h3><p>Complete chapter goals to unlock markets and the Starwatch Tower. Your town saves itself.</p></div></div><div className="guide-keys"><span><kbd>1–9</kbd> choose craft</span><span><kbd>Space</kbd> pause</span><span><kbd>B</kbd> Bloom Rite</span><span><kbd>Esc</kbd> close panels</span></div><button onClick={()=>setShowGuide(false)}>Open the builder’s folio</button></div></div>}
    {showLedger&&<div className="choice-layer" role="dialog" aria-modal="true" aria-labelledby="ledger-title"><div className="ledger-card"><button className="ledger-close" onClick={()=>setShowLedger(false)} aria-label="Close town ledger">×</button><small>THE TOWN LEDGER</small><h2 id="ledger-title">Marks in the margin</h2><p>Small deeds become the stories travelers carry beyond the vale.</p><div className="achievement-grid">{achievements.map(a=><div key={a.name} className={a.done?"earned":""}><span>{a.done?a.icon:"?"}</span><b>{a.name}</b><small>{a.copy}</small></div>)}</div><div className="ledger-summary"><span><b>{achievements.filter(a=>a.done).length}/6</b> marks earned</span><span><b>{deeds}</b> promises kept</span><span><b>{day}</b> days tended</span><span><b>{score}</b> town score</span></div><div className="ledger-title">Current rank · {townTitle}</div></div></div>}
    {finalWin&&<div className="victory" role="dialog" aria-modal="true" aria-labelledby="victory-title"><div className="victory-card"><span>✦</span><small>THE VALE REMEMBERS</small><h2 id="victory-title">Glimmerglen awakens</h2><p>Your folk have woven craft, fellowship, and old magic into a woodland haven worthy of legend.</p><div className="victory-rank"><small>TOWN RANK</small><b>{townTitle}</b><span>{score.toLocaleString()} points</span></div><div className="victory-stats"><b>{day}<small>days</small></b><b>{resources.folk}<small>folk</small></b><b>{renown}<small>renown</small></b></div><button onClick={restart}>Grow another town</button></div></div>}
  </main>
}
function Resource({icon,label,value,rate}:{icon:string;label:string;value:number;rate?:number}){return <div className="resource"><span>{icon}</span><div><small>{label}</small><b>{value}</b></div>{rate!==undefined&&<em className={rate<0?"negative":""}>{rate>=0?"+":""}{rate}/day</em>}</div>}
function Goal({label,value,target}:{label:string;value:number;target:number}){const done=value>=target;return <div className={`goal ${done?"done":""}`}><span>{done?"✓":""}</span><div><b>{label}</b><i><em style={{width:`${Math.min(100,value/target*100)}%`}}/></i></div><small>{Math.min(value,target)}/{target}</small></div>}
function EventChoice({kind,choose}:{kind:"merchant"|"spirit"|"druid"|"storm";choose:(n:number)=>void}){const content={merchant:{icon:"¤",label:"A TRAVELER AT THE WAYSTONE",title:"The Lantern Merchant",copy:"A road-worn trader offers a bargain, but seems even more interested in your supper fire.",a:"Trade 15 wood for 22 stone",b:"Share supper: +18 food, +2 renown"},spirit:{icon:"✦",label:"A VOICE UPON THE WATER",title:"The Spirit of Stillwater",copy:"A river-bright spirit asks what blessing the young town needs most.",a:"Ask for 16 mana",b:"Ask for 24 food"},druid:{icon:"♧",label:"A KEEPER OF OLD ROOTS",title:"The Druid of Greenward",copy:"The western grove has awakened. Its keeper asks whether it should serve the town or remain untouched.",a:"Gather fallen wood: +30 wood, up to −8 mana",b:"Name a sanctuary: +6 renown"},storm:{icon:"☾",label:"THUNDER BEYOND THE CRAGS",title:"The Starstorm",copy:"Blue lightning walks down from the mountains. The town can brace its roofs or invite the storm into its shrines.",a:"Brace the town: −18 wood, +28 stone",b:"Call the lightning: −16 food, +24 mana"}}[kind];return <div className="choice-card"><span>{content.icon}</span><small>{content.label}</small><h2>{content.title}</h2><p>{content.copy}</p><button onClick={()=>choose(0)}>{content.a}</button><button onClick={()=>choose(1)}>{content.b}</button></div>}
